POSTGRES_URL="postgres://default:nltVeB7w5cgb@ep-holy-dew-43447663-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb"
POSTGRES_PRISMA_URL="postgres://default:nltVeB7w5cgb@ep-holy-dew-43447663-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb?pgbouncer=true&connect_timeout=15"
POSTGRES_URL_NON_POOLING="postgres://default:nltVeB7w5cgb@ep-holy-dew-43447663.us-east-1.postgres.vercel-storage.com:5432/verceldb"
POSTGRES_USER="default"
POSTGRES_HOST="ep-holy-dew-43447663-pooler.us-east-1.postgres.vercel-storage.com"
POSTGRES_PASSWORD="nltVeB7w5cgb"
POSTGRES_DATABASE="verceldb"
